### ISSUE TITLE
--disable-save-password-bubble no longer supported by chrome

### ISSUE THREAD

**Issue by johansglock** [loadtestgo/pizzascript#13]
These days chrome requires us to write specific settings to the preferences file. It would be nice to have a generic feature to pass user profile preferences.

The required user profile settings these days should be:
```
credentials_enable_service = false
profile.password_manager_enabled = false
```

**Comment by watsonmw** [comment]
Oh I need to cut a new release with the fix for this:

https://github.com/loadtestgo/pizzascript/commit/b3c4161ef6f4f48b573e02bffef8def19c8e28e3

Adding a generic mechanism to override the user profile is a good idea.  I probably add something to just include overrides to the Preferences.json for now.

**Comment by watsonmw** [comment]
Add a new release with this fix, Cheers!

https://github.com/loadtestgo/pizzascript/releases/tag/0.2.9

**Comment by johansglock** [comment]
awesome, thx!
